import type { Theme } from '../types.js';

const darkShadow = { dx: 2, dy: 3, blur: 5, color: 'rgba(0,0,0,0.45)' };

export const darkTheme: Theme = {
  background: '#333333',
  primaryColor: '#1f2020',
  secondaryColor: '#484848',
  tertiaryColor: '#1f1f1f',
  primaryTextColor: '#e0dfdf',
  secondaryTextColor: '#b8b8b8',
  lineColor: '#d3d3d3',
  borderColor: '#cccccc',
  fontFamily: '"trebuchet ms", verdana, arial, sans-serif',
  fontSize: 14,
  fontWeight: 'normal',
  nodeStyles: {
    default: {
      fill: '#1f2020',
      stroke: '#cccccc',
      strokeWidth: 1.5,
      rx: 5,
      ry: 5,
      textColor: '#e0dfdf',
      padding: 12,
      gradient: { type: 'linear', from: '#2a2b2b', to: '#161717', direction: 180 },
      shadow: darkShadow,
    },
    decision: {
      fill: '#1f2020',
      stroke: '#cccccc',
      strokeWidth: 1.5,
      textColor: '#e0dfdf',
      padding: 12,
      gradient: { type: 'linear', from: '#2a2b2b', to: '#161717', direction: 180 },
      shadow: darkShadow,
    },
    rounded: {
      fill: '#484848',
      stroke: '#cccccc',
      strokeWidth: 1.5,
      rx: 20,
      ry: 20,
      textColor: '#e0dfdf',
      padding: 12,
      gradient: { type: 'linear', from: '#555555', to: '#3a3a3a', direction: 180 },
      shadow: darkShadow,
    },
    circle: {
      fill: '#1f2020',
      stroke: '#cccccc',
      strokeWidth: 1.5,
      textColor: '#e0dfdf',
      padding: 12,
      gradient: { type: 'radial', from: '#2a2b2b', to: '#161717' },
      shadow: darkShadow,
    },
    cylinder: {
      fill: '#484848',
      stroke: '#cccccc',
      strokeWidth: 1.5,
      textColor: '#e0dfdf',
      padding: 12,
      gradient: { type: 'linear', from: '#555555', to: '#3a3a3a', direction: 180 },
      shadow: darkShadow,
    },
    subroutine: {
      fill: '#1f2020',
      stroke: '#cccccc',
      strokeWidth: 1.5,
      rx: 0,
      ry: 0,
      textColor: '#e0dfdf',
      padding: 12,
      gradient: { type: 'linear', from: '#2a2b2b', to: '#161717', direction: 180 },
      shadow: darkShadow,
    },
  },
  edgeStyles: {
    default: {
      stroke: '#d3d3d3',
      strokeWidth: 1.5,
      arrowColor: '#d3d3d3',
      labelBackground: '#585858',
      labelColor: '#cccccc',
    },
    dotted: {
      stroke: '#d3d3d3',
      strokeWidth: 1.5,
      strokeDasharray: '5,5',
      arrowColor: '#d3d3d3',
      labelBackground: '#585858',
      labelColor: '#cccccc',
    },
    thick: {
      stroke: '#d3d3d3',
      strokeWidth: 3,
      arrowColor: '#d3d3d3',
      labelBackground: '#585858',
      labelColor: '#e0dfdf',
    },
  },
};

