import type { Theme } from '../types.js';

const defaultShadow = { dx: 2, dy: 3, blur: 4, color: 'rgba(0,0,0,0.15)' };

export const defaultTheme: Theme = {
  background: '#ffffff',
  primaryColor: '#ECECFF',
  secondaryColor: '#ffffde',
  tertiaryColor: '#f5f5f0',
  primaryTextColor: '#131300',
  secondaryTextColor: '#000021',
  lineColor: '#333333',
  borderColor: '#9370DB',
  fontFamily: '"trebuchet ms", verdana, arial, sans-serif',
  fontSize: 14,
  fontWeight: 'normal',
  nodeStyles: {
    default: {
      fill: '#ECECFF',
      stroke: '#9370DB',
      strokeWidth: 1.5,
      rx: 5,
      ry: 5,
      textColor: '#131300',
      padding: 12,
      gradient: { type: 'linear', from: '#f8f8ff', to: '#DCDCFF', direction: 180 },
      shadow: defaultShadow,
    },
    decision: {
      fill: '#ECECFF',
      stroke: '#9370DB',
      strokeWidth: 1.5,
      textColor: '#131300',
      padding: 12,
      gradient: { type: 'linear', from: '#f8f8ff', to: '#DCDCFF', direction: 180 },
      shadow: defaultShadow,
    },
    rounded: {
      fill: '#ffffde',
      stroke: '#aaaa33',
      strokeWidth: 1.5,
      rx: 20,
      ry: 20,
      textColor: '#131300',
      padding: 12,
      gradient: { type: 'linear', from: '#fffff0', to: '#f5f5c0', direction: 180 },
      shadow: defaultShadow,
    },
    circle: {
      fill: '#ECECFF',
      stroke: '#9370DB',
      strokeWidth: 1.5,
      textColor: '#131300',
      padding: 12,
      gradient: { type: 'radial', from: '#f8f8ff', to: '#DCDCFF' },
      shadow: defaultShadow,
    },
    cylinder: {
      fill: '#ffffde',
      stroke: '#aaaa33',
      strokeWidth: 1.5,
      textColor: '#131300',
      padding: 12,
      gradient: { type: 'linear', from: '#fffff0', to: '#f5f5c0', direction: 180 },
      shadow: defaultShadow,
    },
    subroutine: {
      fill: '#f5f5f0',
      stroke: '#9370DB',
      strokeWidth: 1.5,
      rx: 0,
      ry: 0,
      textColor: '#131300',
      padding: 12,
      gradient: { type: 'linear', from: '#fafaf5', to: '#eaeae0', direction: 180 },
      shadow: defaultShadow,
    },
  },
  edgeStyles: {
    default: {
      stroke: '#333333',
      strokeWidth: 1.5,
      arrowColor: '#333333',
      labelBackground: 'rgba(232,232,232,0.8)',
      labelColor: '#333333',
    },
    dotted: {
      stroke: '#333333',
      strokeWidth: 1.5,
      strokeDasharray: '5,5',
      arrowColor: '#333333',
      labelBackground: 'rgba(232,232,232,0.8)',
      labelColor: '#333333',
    },
    thick: {
      stroke: '#333333',
      strokeWidth: 3,
      arrowColor: '#333333',
      labelBackground: 'rgba(232,232,232,0.8)',
      labelColor: '#131300',
    },
  },
};
