import type { Theme } from '../types.js';

const neutralShadow = { dx: 1, dy: 2, blur: 3, color: 'rgba(0,0,0,0.12)' };

export const neutralTheme: Theme = {
  background: '#ffffff',
  primaryColor: '#eeeeee',
  secondaryColor: '#fcfcfc',
  tertiaryColor: '#eeeeee',
  primaryTextColor: '#111111',
  secondaryTextColor: '#333333',
  lineColor: '#666666',
  borderColor: '#999999',
  fontFamily: '"trebuchet ms", verdana, arial, sans-serif',
  fontSize: 14,
  fontWeight: 'normal',
  nodeStyles: {
    default: {
      fill: '#eeeeee',
      stroke: '#999999',
      strokeWidth: 1.5,
      rx: 5,
      ry: 5,
      textColor: '#111111',
      padding: 12,
      gradient: { type: 'linear', from: '#f8f8f8', to: '#e0e0e0', direction: 180 },
      shadow: neutralShadow,
    },
    decision: {
      fill: '#eeeeee',
      stroke: '#999999',
      strokeWidth: 1.5,
      textColor: '#111111',
      padding: 12,
      gradient: { type: 'linear', from: '#f8f8f8', to: '#e0e0e0', direction: 180 },
      shadow: neutralShadow,
    },
    rounded: {
      fill: '#fcfcfc',
      stroke: '#707070',
      strokeWidth: 1.5,
      rx: 20,
      ry: 20,
      textColor: '#111111',
      padding: 12,
      gradient: { type: 'linear', from: '#ffffff', to: '#f0f0f0', direction: 180 },
      shadow: neutralShadow,
    },
    circle: {
      fill: '#eeeeee',
      stroke: '#999999',
      strokeWidth: 1.5,
      textColor: '#111111',
      padding: 12,
      gradient: { type: 'radial', from: '#f8f8f8', to: '#e0e0e0' },
      shadow: neutralShadow,
    },
    cylinder: {
      fill: '#fcfcfc',
      stroke: '#707070',
      strokeWidth: 1.5,
      textColor: '#111111',
      padding: 12,
      gradient: { type: 'linear', from: '#ffffff', to: '#f0f0f0', direction: 180 },
      shadow: neutralShadow,
    },
    subroutine: {
      fill: '#eeeeee',
      stroke: '#999999',
      strokeWidth: 1.5,
      rx: 0,
      ry: 0,
      textColor: '#111111',
      padding: 12,
      gradient: { type: 'linear', from: '#f8f8f8', to: '#e0e0e0', direction: 180 },
      shadow: neutralShadow,
    },
  },
  edgeStyles: {
    default: {
      stroke: '#666666',
      strokeWidth: 1.5,
      arrowColor: '#333333',
      labelBackground: '#ffffff',
      labelColor: '#333333',
    },
    dotted: {
      stroke: '#666666',
      strokeWidth: 1.5,
      strokeDasharray: '5,5',
      arrowColor: '#333333',
      labelBackground: '#ffffff',
      labelColor: '#333333',
    },
    thick: {
      stroke: '#666666',
      strokeWidth: 3,
      arrowColor: '#333333',
      labelBackground: '#ffffff',
      labelColor: '#111111',
    },
  },
};
