classDiagram
  class Animal {
    +int age
    +String gender
    +isMammal() bool
    +mate()
  }
  class Duck {
    +String beakColor
    +swim()
    +quack()
  }
  class Fish {
    -int sizeInFeet
    +canEat()
  }
  Animal <|-- Duck
  Animal <|-- Fish

